---
- name: Install nginx
  hosts: all
  become: true
  gather_facts: False

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        update_cache: yes

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes

